version: '3.9'

networks:
  dotLanchesPedidoNetwork:
    driver: bridge

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sudowoodo
      MONGO_INITDB_ROOT_PASSWORD: P455w0rd
    ports:
    - "27017:27017" 
    networks:
      - dotLanchesPedidoNetwork

  api:
    build: 
      context: .
      dockerfile: ./src/FrameworksAndDrivers/Web/DotLanches.Pedidos.Api/Dockerfile
    container_name: dotlanches_pedido_api
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=mongodb://sudowoodo:P455w0rd@db:27017/?appName=dotlanche
    networks:
      - dotLanchesPedidoNetwork
