apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dotlanche-pedido-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotlanche-pedido-deployment
  minReplicas: 2
  maxReplicas: 7
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 30